name: deploy-blog

on:
  push:
    branches: [master]

jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    name: deploy-blog
    steps:
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master
        run: ls

      - name: Build
        run: |
          cd master
          npm ci
          echo before build---
          ls
          npm run build
          echo after build---
          ls

      - uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: gh-pages
          run: ls

      - name: Deployment
        run: |
          rsync master/dist/ gh-pages/
          cd gh-pages
          ls
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Deployment"
          git push
