name: deploy-blog

on:
  push:
    branches: [master]

jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    name: deploy-blog
    steps:
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master

      # - name: Install dependencies
      #   run: cd master && npm ci

      # - name: Build
      #   run: cd master && npm run build

      - uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: gh-pages

      - name: Deployment
        run: |
          ls
          rsync master/package.json gh-pages/1313.json
          cd gh-pages
          ls