name: deploy-blog

on:
  push:
    branches: [master]

jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    name: deploy-blog
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: Install dependencies
        run: cd master && npm ci

      - name: Build
        run: cd master npm run build

      - name: ls
        run: cd master && ls

      # - uses: actions/checkout@v2
      #   with:
      #     path: gh-pages
      #     ref: gh-pages

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'

      # - name: Install dependencies
      #   run: npm ci
