name: deploy-blog

on:
  push:
    branches: [master]

jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    name: deploy-blog
    steps:
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: ls master
        run: cd master && ls

      - name: Build
        run: |
          cd master
          npm ci
          echo before build---
          ls
          npm run build
          echo after build---
          ls

      - uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: gh-pages

      - name: Clean gh-pages directory
        run: ls | grep -v .git | xargs rm -rf

      - name: ls gh-pages
        run: cd gh-pages && ls

      - name: Copy dist folder from master to gh-pages
        uses: canastro/copy-file-action@master
        with:
          source: master/dist/.
          target: gh-pages/
          flags: '-r'

      - name: Deployment
        run: |
          cd gh-pages
          ls
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet && git diff --staged --quiet || git commit -am "Deployment"
          git push
